name: Docker Image CI on PR

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build-test-scan:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:1.0.0
    
    - name: Run tests
      run: echo "Test"

    # Scan the Docker image with Trivy
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-image-name:1.0.0
        format: table 
        severity: HIGH,CRITICAL
